name: Log de modificações pro DC

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Enviar embed pro Discord
        run: |
          LAST_COMMIT_HASH=$(git log -1 --pretty=format:'%h')
